### ISSUE TITLE
Step 3 needs more content

### ISSUE THREAD

**Issue by TheHassanShahzad** [VModugno/RoboEnv#4]
Step 3 doesn't explain the correct steps.

Should clone from https://github.com/VModugno/lab_sessions_COMP0245_PUBLIC into simulation and modelling folder and take model and config folders into week 1

**Comment by VModugno** [comment]
thank you for your feedback I'll update the README accordingly, i have been told by many students that they were looking for a main.py file which does not exist and it was meant to be only an example to refer to the current script you are working with
